name=espnow2serial
version=0.1
author= Simon D. Levy<simon.d.levy@gmail.com>
maintainer=Simon D. Levy<simon.d.levy@gmail.com>
sentence=ESPNOW / Serial relay utility for Arduino
paragraph=
category=Other
url=https://github.com/simondlevy/espnow2serial
architectures=*
includes=espnow2serial.h
